#!/bin/sh -e

export CCACHE_SLOPPINESS=time_macros,include_file_mtime

# Have webkit play nicer with ccache (taken from Void).
for f in Source/WebCore/bindings/scripts/CodeGenerator.pm \
    Source/WebCore/bindings/scripts/CodeGeneratorJS.pm \
    Source/WebCore/css/makeprop.pl \
    Source/cmake/tools/scripts/version-stamp.pl; do
    sed -e '/foreach my.*(keys/s/(keys/(sort keys/' "$f" > _
    mv -f _ "$f"
    done

# Webkit's CMake configuration forces color output using clang-specific flags
# when using Ninja as the CMAKE_GENERATOR. We should disable them.
sed "s/-fcolor-diagnostics//" Source/cmake/WebKitCompilerFlags.cmake > _
mv -f _ Source/cmake/WebKitCompilerFlags.cmake


patch -p1 < 2.34.3-non-jumbo-fix.patch
patch -p1 < 2.34.3-opengl-without-X-fixes.patch
patch -p1 < 0001-Fix-build-without-opengl-or-es.patch?

# Remove gettext requirement.
sed -i 's/ngettext/printf/g' Tools/MiniBrowser/gtk/BrowserDownloadsBar.c
sed -i '/po_files \*\.po/d'  Source/WebCore/platform/gtk/po/CMakeLists.txt
sed -i '/^GETTEXT_C/d'       Source/WebCore/platform/gtk/po/CMakeLists.txt

# Fix clang build.
sed -i '/LC_ALL/d'       Source/JavaScriptCore/jsc.cpp
sed -i '/WTFLogAlways/d' Source/JavaScriptCore/jsc.cpp

# Reduce memory usage.
export LDFLAGS="$LDFLAGS -Wl,--no-keep-memory"

cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBEXECDIR=/usr/lib \
    -DLIB_INSTALL_DIR=/usr/lib \
    -DPORT=GTK \
    -DCMAKE_SKIP_RPATH=ON \
    -DENABLE_UNIFIED_BUILDS=ON \
    -DENABLE_BUBBLEWRAP_SANDBOX=OFF \
    -DENABLE_SAMPLING_PROFILER=OFF \
    -DENABLE_GAMEPAD=OFF \
    -DENABLE_GEOLOCATION=OFF \
    -DENABLE_GLES2=ON \
    -DENABLE_INTROSPECTION=OFF \
    -DENABLE_MINIBROWSER=OFF \
    -DENABLE_SPELLCHECK=OFF \
    -DENABLE_WEBGL=OFF \
    -DENABLE_WEBGL2=OFF \
    -DENABLE_WEBDRIVER=OFF \
    -DENABLE_WEB_CRYPTO=OFF \
    -DENABLE_VIDEO=OFF \
    -DENABLE_WEB_AUDIO=OFF \
    -DUSE_GSTREAMER_GL=OFF \
    -DUSE_LIBHYPHEN=OFF \
    -DUSE_LIBNOTIFY=OFF \
    -DUSE_LIBSECRET=OFF \
    -DUSE_OPENGL_OR_ES=OFF \
    -DUSE_SYSTEMD=OFF \
    -DUSE_WOFF2=OFF \
    -DUSE_WPE_RENDERER=OFF \
    -DUSE_OPENJPEG=OFF \
    -DUSE_SOUP2=ON \
    -Wno-dev

cmake --build   build
cmake --install build
