#!/bin/sh -e

patch -p1 < dropbear-options_sftp-server_path.patch

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --enable-static

make PROGRAMS="dropbear dropbearkey dbclient dropbearconvert scp"
make PROGRAMS="dropbear dropbearkey dbclient dropbearconvert scp" DESTDIR="$1" install

ln -s dbclient "$1/usr/bin/ssh"

# Install user services
mkdir -p                              "$1/etc/sv/dropbear"
cp -f dropbear.run                    "$1/etc/sv/dropbear/run"
ln -sf /run/runit/supervice.dropbear  "$1/etc/sv/dropbear/supervise"

# Make the sftp-server from Openssh.
(
	cd sftp
	./configure
	make sftp-server

	mkdir -p          "$1/usr/lib/dropbear"
	cp -f sftp-server "$1/usr/lib/dropbear/sftp-server"

	
)
