#!/bin/sh -e

CFLAGS="-DNCURSESW_INCLUDE_H=\<ncurses.h\> $CFLAGS"

make

mkdir -p \
    "$1/usr/bin/" \
    "$1/usr/share/man/man1"

# instead of altering the Makefile, we just copy the wanted files
cp mtm "$1/usr/bin" 
cp mtm.1 "$1/usr/share/man/man1"
