#!/bin/sh -e

# Force a static build so shared library breakage does not also break the
# linker (and therefore the ability to recover from the issue).
export EXTRA_LDFLAGS="$LDFLAGS -static"

make PREFIX=/usr
make PREFIX=/usr install

# Create a symbolic link so users can use mold as the linker system-wide
# (without need for special CFLAGS/CXXFLAGS).
ln -s mold "$1/usr/bin/ld"

# To tell GCC to use mold we must put a symlink to it in a directory and set it
# to search for the linker within.
ln -s ../../bin/mold "$1/usr/lib/mold/ld"
