#!/bin/sh -e

export CFLAGS="$CFLAGS -fcommon"
export PATH="$PATH:$PWD/xxd"
export NETSURF_HOMEPAGE=https://google.de

# Buidl standalone xxd to remove VIM requirement.
cc xxd/xxd.c -o xxd/xxd

rm -rf netsurf
rm -rf libcss

git clone git://git.netsurf-browser.org/libcss.git
git clone https://git.sr.ht/~sircmpwn/visurf
mv visurf netsurf

make \
    LIBDIR=lib \
    INCLUDEDIR=include \
    PREFIX=/usr \
    TARGET=visurf

make \
    LIBDIR=lib \
    INCLUDEDIR=include \
    PREFIX=/usr \
    TARGET=visurf \
    DESTDIR="$1" \
    install
