#!/bin/sh -e

#patch -p1 < fix-build-against-wayland-1.20.patch
#patch -p1 < patch-src_audio_sndio_SDL_sndioaudio_c src/audio/sndio/SDL_sndioaudio.c

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DSDL_SNDIO=ON \
    -DSDL_OPENGL=OFF \
    -DSDL_OPENGLES=ON
    

cmake --build   build
cmake --install build
