#!/bin/sh -e

patch -p1 < fix-build-against-wayland-1.20.patch

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DSDL_OPENGL=OFF \
    -DSDL_OPENGLES=ON \
    -DSDL_SNDIO=ON
    

cmake --build   build
cmake --install build
