#!/bin/sh -e

# Adding explanations of various capabilities to capsh requires a bash script.
#patch -p1 < no-capshdoc.patch

mk() {
    make \
        GOLANG=no \
        PREFIX=/usr \
        SBINDIR=/usr/bin \
        LIBDIR=/usr/lib \
        PKGCONFIGDIR=/usr/lib/pkgconfig \
        RAISE_SETFCAP=no \
        INDENT=" " \
        "$@"

}
mk
mk DESTDIR="$1" install
