#!/bin/sh -e

# Build libepoxy for gtk+3's sole use. This is the only package that requires
# the library. While the build system supports building this as a subproject,
# it is broken so we must do it ourselves.
(
    cd libepoxy

    meson \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        -Ddefault_library=static \
        -Degl=yes \
        -Dtests=false \
        -Dglx=no \
        -Dx11=false \
        . output

    ninja -C output

    DESTDIR=$PWD ninja -C output install
)

# Point gtk+3 to the vendored libepoxy.
export PKG_CONFIG_PATH=$PWD/libepoxy/usr/lib/pkgconfig
export CFLAGS="$CFLAGS -L$PWD/libepoxy/usr/lib"
export CFLAGS="$CFLAGS -I$PWD/libepoxy/usr/include"

meson \
    --prefix=/usr \
    --buildtype=release \
    . output

ninja -C output
ninja -C output install
